// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
// Re-run `npm run catalog` after adding/renaming images.

export interface CategoryFAQ { question: string; answer: string; }
export interface Category {
  id: string; name: string; slug: string; shortLabel: string;
  description: string; intro: string; seoTitle: string; seoDescription: string;
  keywords: string[]; heroImage: string; image: string; icon: string;
  productCount: number; faq: CategoryFAQ[]; relatedSlugs: string[];
}

export const categories: Category[] = [
  {
    "id": "bloc-notes-carnets-bureau-personnalises-maroc",
    "name": "Bloc-notes, carnets et articles de bureau personnalisés",
    "slug": "bloc-notes-carnets-bureau-personnalises-maroc",
    "shortLabel": "Bureautique",
    "description": "Découvrez notre sélection de bloc-notes, carnets et articles de bureau personnalisés avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des bloc-notes, carnets et articles de bureau personnalisés pour les entreprises marocaines. Bureautique de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Bloc-notes, carnets et articles de bureau personnalisés | Nova Gift Maroc",
    "seoDescription": "Bloc-notes, carnets et articles de bureau personnalisés avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "bloc-notes, carnets et articles de bureau personnalisés",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/bloc-notes-carnets-bureau-personnalises-maroc/agenda-a-poche-en-similicuir-personnalise/casablanca.webp",
    "image": "/products/bloc-notes-carnets-bureau-personnalises-maroc/agenda-a-poche-en-similicuir-personnalise/casablanca.webp",
    "icon": "📓",
    "productCount": 26,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les bureautique personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons gravure laser, dorure à chaud, impression logo selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "coffrets-cadeaux-entreprise-personnalises-maroc",
      "bracelets-evenementiels-objets-personnalises-maroc",
      "gourdes-mugs-bouteilles-personnalises-maroc"
    ]
  },
  {
    "id": "coffrets-cadeaux-entreprise-personnalises-maroc",
    "name": "Coffrets cadeaux d'entreprise personnalisés",
    "slug": "coffrets-cadeaux-entreprise-personnalises-maroc",
    "shortLabel": "Coffrets",
    "description": "Découvrez notre sélection de coffrets cadeaux d'entreprise personnalisés avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des coffrets cadeaux d'entreprise personnalisés pour les entreprises marocaines. Coffrets de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Coffrets cadeaux d'entreprise personnalisés | Nova Gift Maroc",
    "seoDescription": "Coffrets cadeaux d'entreprise personnalisés avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "coffrets cadeaux d'entreprise personnalisés",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/coffrets-cadeaux-entreprise-personnalises-maroc/coffret-cadeau-vip-haut-de-gamme-personnalise/casablanca.webp",
    "image": "/products/coffrets-cadeaux-entreprise-personnalises-maroc/coffret-cadeau-vip-haut-de-gamme-personnalise/casablanca.webp",
    "icon": "🎁",
    "productCount": 13,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les coffrets personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons gravure laser, impression logo, marquage à chaud selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "bloc-notes-carnets-bureau-personnalises-maroc",
      "bracelets-evenementiels-objets-personnalises-maroc",
      "gourdes-mugs-bouteilles-personnalises-maroc"
    ]
  },
  {
    "id": "bracelets-evenementiels-objets-personnalises-maroc",
    "name": "Bracelets événementiels et objets personnalisés pour événements",
    "slug": "bracelets-evenementiels-objets-personnalises-maroc",
    "shortLabel": "Événementiel",
    "description": "Découvrez notre sélection de bracelets événementiels et objets personnalisés pour événements avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des bracelets événementiels et objets personnalisés pour événements pour les entreprises marocaines. Événementiel de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Bracelets événementiels et objets personnalisés pour événements | Nova Gift Maroc",
    "seoDescription": "Bracelets événementiels et objets personnalisés pour événements avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "bracelets événementiels et objets personnalisés pour événements",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/bracelets-evenementiels-objets-personnalises-maroc/bracelet-en-silicone-personnalise/casablanca.webp",
    "image": "/products/bracelets-evenementiels-objets-personnalises-maroc/bracelet-en-silicone-personnalise/casablanca.webp",
    "icon": "🎫",
    "productCount": 10,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les événementiel personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons impression couleur, sérigraphie, marquage logo selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "bloc-notes-carnets-bureau-personnalises-maroc",
      "coffrets-cadeaux-entreprise-personnalises-maroc",
      "gourdes-mugs-bouteilles-personnalises-maroc"
    ]
  },
  {
    "id": "gourdes-mugs-bouteilles-personnalises-maroc",
    "name": "Gourdes, mugs et bouteilles personnalisés",
    "slug": "gourdes-mugs-bouteilles-personnalises-maroc",
    "shortLabel": "Gourdes & Mugs",
    "description": "Découvrez notre sélection de gourdes, mugs et bouteilles personnalisés avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des gourdes, mugs et bouteilles personnalisés pour les entreprises marocaines. Gourdes & Mugs de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Gourdes, mugs et bouteilles personnalisés | Nova Gift Maroc",
    "seoDescription": "Gourdes, mugs et bouteilles personnalisés avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "gourdes, mugs et bouteilles personnalisés",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/gourdes-mugs-bouteilles-personnalises-maroc/gourde-personnalisable-personnalise/tanger.webp",
    "image": "/products/gourdes-mugs-bouteilles-personnalises-maroc/gourde-personnalisable-personnalise/tanger.webp",
    "icon": "🥤",
    "productCount": 8,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les gourdes & mugs personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons gravure laser, impression uv, sérigraphie selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "bloc-notes-carnets-bureau-personnalises-maroc",
      "coffrets-cadeaux-entreprise-personnalises-maroc",
      "bracelets-evenementiels-objets-personnalises-maroc"
    ]
  },
  {
    "id": "objets-high-tech-personnalises-maroc",
    "name": "Objets high-tech personnalisés",
    "slug": "objets-high-tech-personnalises-maroc",
    "shortLabel": "High-Tech",
    "description": "Découvrez notre sélection de objets high-tech personnalisés avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des objets high-tech personnalisés pour les entreprises marocaines. High-Tech de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Objets high-tech personnalisés | Nova Gift Maroc",
    "seoDescription": "Objets high-tech personnalisés avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "objets high-tech personnalisés",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/objets-high-tech-personnalises-maroc/cable-multicharge-4-sorties-personnalise/casablanca.webp",
    "image": "/products/objets-high-tech-personnalises-maroc/cable-multicharge-4-sorties-personnalise/casablanca.webp",
    "icon": "🔌",
    "productCount": 15,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les high-tech personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons gravure laser, impression uv, marquage logo selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "bloc-notes-carnets-bureau-personnalises-maroc",
      "coffrets-cadeaux-entreprise-personnalises-maroc",
      "bracelets-evenementiels-objets-personnalises-maroc"
    ]
  },
  {
    "id": "porte-cles-personnalises-pas-chers-maroc",
    "name": "Porte-clés personnalisés pas chers",
    "slug": "porte-cles-personnalises-pas-chers-maroc",
    "shortLabel": "Porte-clés",
    "description": "Découvrez notre sélection de porte-clés personnalisés pas chers avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des porte-clés personnalisés pas chers pour les entreprises marocaines. Porte-clés de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Porte-clés personnalisés pas chers | Nova Gift Maroc",
    "seoDescription": "Porte-clés personnalisés pas chers avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "porte-clés personnalisés pas chers",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/porte-cles-personnalises-pas-chers-maroc/porte-cles-forme-voiture-personnalise/casablanca.webp",
    "image": "/products/porte-cles-personnalises-pas-chers-maroc/porte-cles-forme-voiture-personnalise/casablanca.webp",
    "icon": "🔑",
    "productCount": 6,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les porte-clés personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons impression logo, gravure, marquage couleur selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "bloc-notes-carnets-bureau-personnalises-maroc",
      "coffrets-cadeaux-entreprise-personnalises-maroc",
      "bracelets-evenementiels-objets-personnalises-maroc"
    ]
  },
  {
    "id": "textile-tote-bags-sacs-personnalises-maroc",
    "name": "Textile, tote bags et sacs personnalisés",
    "slug": "textile-tote-bags-sacs-personnalises-maroc",
    "shortLabel": "Textile & Sacs",
    "description": "Découvrez notre sélection de textile, tote bags et sacs personnalisés avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des textile, tote bags et sacs personnalisés pour les entreprises marocaines. Textile & Sacs de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Textile, tote bags et sacs personnalisés | Nova Gift Maroc",
    "seoDescription": "Textile, tote bags et sacs personnalisés avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "textile, tote bags et sacs personnalisés",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/textile-tote-bags-sacs-personnalises-maroc/casquette-brodee-personnalise/casablanca.webp",
    "image": "/products/textile-tote-bags-sacs-personnalises-maroc/casquette-brodee-personnalise/casablanca.webp",
    "icon": "👕",
    "productCount": 12,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les textile & sacs personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons broderie, sérigraphie, flocage selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "bloc-notes-carnets-bureau-personnalises-maroc",
      "coffrets-cadeaux-entreprise-personnalises-maroc",
      "bracelets-evenementiels-objets-personnalises-maroc"
    ]
  },
  {
    "id": "trophees-coupes-recompenses-personnalises-maroc",
    "name": "Trophées, coupes et récompenses personnalisés",
    "slug": "trophees-coupes-recompenses-personnalises-maroc",
    "shortLabel": "Trophées",
    "description": "Découvrez notre sélection de trophées, coupes et récompenses personnalisés avec logo pour entreprises au Maroc. Idéal pour événements, cadeaux clients et communication professionnelle à Casablanca, Rabat, Marrakech et Tanger.",
    "intro": "Nova Gift conçoit des trophées, coupes et récompenses personnalisés pour les entreprises marocaines. Trophées de qualité, marquage personnalisé (logo, couleurs) et livraison partout au Maroc. Demandez un devis gratuit sous 48h.",
    "seoTitle": "Trophées, coupes et récompenses personnalisés | Nova Gift Maroc",
    "seoDescription": "Trophées, coupes et récompenses personnalisés avec logo au Maroc. Marquage de qualité, devis gratuit sous 48h. Livraison Casablanca, Rabat, Marrakech, Tanger.",
    "keywords": [
      "trophées, coupes et récompenses personnalisés",
      "objets publicitaires",
      "cadeaux d'entreprise",
      "personnalisé",
      "avec logo",
      "Maroc",
      "Casablanca",
      "Rabat"
    ],
    "heroImage": "/products/trophees-coupes-recompenses-personnalises-maroc/trophee-personnalise/tanger.webp",
    "image": "/products/trophees-coupes-recompenses-personnalises-maroc/trophee-personnalise/tanger.webp",
    "icon": "🏆",
    "productCount": 3,
    "faq": [
      {
        "question": "Quelle est la quantité minimum pour les trophées personnalisés ?",
        "answer": "La plupart de nos articles sont disponibles à partir de 50 pièces (100 pièces pour les petits objets). Contactez-nous pour les quantités exactes."
      },
      {
        "question": "Quelles techniques de personnalisation proposez-vous ?",
        "answer": "Nous proposons gravure laser, impression uv, marquage logo selon le produit, avec votre logo et vos couleurs."
      },
      {
        "question": "Livrez-vous partout au Maroc ?",
        "answer": "Oui, nous livrons partout au Maroc : Casablanca, Rabat, Marrakech, Tanger et toutes les villes."
      }
    ],
    "relatedSlugs": [
      "bloc-notes-carnets-bureau-personnalises-maroc",
      "coffrets-cadeaux-entreprise-personnalises-maroc",
      "bracelets-evenementiels-objets-personnalises-maroc"
    ]
  }
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
